"""Run release validation and build the canonical distribution set.

The release workflow uses the PEP 517 build as a packaging validation check,
then publishes the deterministic output from ``build_dist.py`` and the SBOM
generated by ``generate_sbom.py``.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]


def run(command: list[str]) -> None:
    print("+", " ".join(command), flush=True)
    env = os.environ.copy()
    source_path = str(ROOT / "src")
    env["PYTHONPATH"] = source_path + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    subprocess.run(command, cwd=ROOT, check=True, env=env)


def check_version_consistency(tag: str | None = None) -> None:
    version = (ROOT / "src" / "proofdiff" / "_version.py").read_text(encoding="utf-8").split('"')[1]
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    citation = (ROOT / "CITATION.cff").read_text(encoding="utf-8")
    if version not in changelog or f"version: {version}" not in citation:
        raise SystemExit("version metadata is inconsistent")
    if tag is None:
        print("Tag/version check skipped: no release tag supplied")
        return
    if not re.fullmatch(r"v\d+\.\d+\.\d+(?:rc\d+)?", tag):
        raise SystemExit(f"invalid release tag {tag!r}; expected vX.Y.Z or vX.Y.ZrcN")
    expected_tag = f"v{version}"
    if tag != expected_tag:
        raise SystemExit(f"tag/version mismatch: {tag} does not match package version {version}")
    print(f"Tag/version check passed: {tag}")


def static_scan() -> None:
    forbidden = {
        r"\beval\s*\(": "eval",
        r"\bexec\s*\(": "exec",
        r"shell\s*=\s*True": "shell=True",
        r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----": "private key",
    }
    findings: list[str] = []
    for path in sorted((ROOT / "src").rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        for pattern, label in forbidden.items():
            if re.search(pattern, text):
                findings.append(f"{path.relative_to(ROOT)}: {label}")
    if findings:
        raise SystemExit("static scan findings:\n" + "\n".join(findings))
    print("Static scan passed")


def main() -> int:
    parser = argparse.ArgumentParser(description="Run ProofDiff release validation")
    parser.add_argument("--tag", help="Release tag to validate against the package version")
    args = parser.parse_args()
    check_version_consistency(args.tag)
    static_scan()
    run([sys.executable, "-m", "compileall", "-q", "src", "tests", "scripts", "benchmarks"])
    if importlib.util.find_spec("ruff"):
        run([sys.executable, "-m", "ruff", "check", "."])
    else:
        print("Ruff unavailable locally; CI remains authoritative")
    if importlib.util.find_spec("mypy"):
        run([sys.executable, "-m", "mypy", "src/proofdiff"])
    else:
        print("mypy unavailable locally; CI remains authoritative")
    run([sys.executable, "-m", "coverage", "erase"])
    run([sys.executable, "-m", "coverage", "run", "--branch", "-m", "pytest", "-q"])
    run([sys.executable, "-m", "coverage", "report", "-m"])
    run([sys.executable, "scripts/check_schemas.py"])
    run([sys.executable, "scripts/check_architecture.py"])
    run([sys.executable, "scripts/security_scan.py"])
    run([sys.executable, "benchmarks/run_benchmark.py", "--no-write"])
    run([sys.executable, "scripts/build_dist.py"])
    distributions = [
        *sorted((ROOT / "dist").glob("*.whl")),
        *sorted((ROOT / "dist").glob("*.tar.gz")),
    ]
    if not distributions:
        raise SystemExit("release build produced no distributions")
    run(
        [
            sys.executable,
            "-m",
            "twine",
            "check",
            *(str(path) for path in distributions),
        ]
    )
    run([sys.executable, "scripts/generate_sbom.py"])
    run([sys.executable, "scripts/smoke_install.py"])
    print("Release checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
